keys:
  - &user_julian age177xlgxsvy7pacq7t28s658ptk2aaecvhyzvyqumayfgcqth3ldwscr792q
  - &host_junixos age14sseru3gn4gruxuf7xgadjauyw78truclpcyedkzvfn7lvcqj5xqc6ejrc
  # Add junixbook host key when ready
  # - &host_junixbook age1...

creation_rules:
  - path_regex: secrets/common\.yaml$
    key_groups:
      - age:
          - *user_julian
          - *host_junixos
  - path_regex: secrets/junixos\.yaml$
    key_groups:
      - age:
          - *user_julian
          - *host_junixos
  - path_regex: secrets/junixbook\.yaml$
    key_groups:
      - age:
          - *user_julian
  - path_regex: secrets/users/[^/]+\.yaml$
    key_groups:
      - age:
          - *user_julian
          - *host_junixos
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *user_julian
          - *host_junixos
