keys:
  - &user_julian age177xlgxsvy7pacq7t28s658ptk2aaecvhyzvyqumayfgcqth3ldwscr792q
  - &host_junixos age14sseru3gn4gruxuf7xgadjauyw78truclpcyedkzvfn7lvcqj5xqc6ejrc
  - &host_junixbook age1myg9n8p9ds5f2sle4f04a56v5r7cpgf87cgrfgqcm78c3g4aaa0qfm4tvw

creation_rules:
  - path_regex: secrets/common\.yaml$
    key_groups:
      - age:
          - *user_julian
          - *host_junixos
          - *host_junixbook
  - path_regex: secrets/junixos\.yaml$
    key_groups:
      - age:
          - *user_julian
          - *host_junixos
  - path_regex: secrets/junixbook\.yaml$
    key_groups:
      - age:
          - *user_julian
          - *host_junixbook
  - path_regex: secrets/users/[^/]+\.yaml$
    key_groups:
      - age:
          - *user_julian
          - *host_junixos
          - *host_junixbook
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *user_julian
          - *host_junixos
          - *host_junixbook
