name: "Nix Auto-Update"

on:
  schedule:
    - cron: "26 2 * * *" # Runs daily at 2:26 AM UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  update:
    name: Update Flake Lockfile
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.WALLPAPER_DEPLOY_KEY }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16

      - name: Check for nixpkgs updates
        id: check-update
        run: |
          if [ "${{ github.event_name }}" = "schedule" ]; then
            nix flake update nixpkgs
            
            if git diff --quiet flake.lock; then
              echo "No updates available for nixpkgs. Skipping further updates."
              echo "run_update=false" >> "$GITHUB_OUTPUT"
            else
              echo "New nixpkgs version found. Proceeding with a full update."
              echo "run_update=true" >> "$GITHUB_OUTPUT"
            fi
          else
            echo "Manual trigger. Running update."
            echo "run_update=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Update remaining inputs
        if: steps.check-update.outputs.run_update == 'true'
        run: nix flake update

      - name: Evaluate junixos
        if: steps.check-update.outputs.run_update == 'true'
        run: nix eval .#nixosConfigurations.junixos.config.system.build.toplevel.drvPath --show-trace

      - name: Evaluate junixbook
        if: steps.check-update.outputs.run_update == 'true'
        run: nix eval .#nixosConfigurations.junixbook.config.system.build.toplevel.drvPath --show-trace

      - name: Commit and push changes
        if: steps.check-update.outputs.run_update == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(flake): update inputs"
          file_pattern: "flake.lock"
