name: "Nix Eval Check"

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Evaluate NixOS Configurations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.WALLPAPER_DEPLOY_KEY }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16

      - name: Evaluate junixos
        run: nix eval .#nixosConfigurations.junixos.config.system.build.toplevel.drvPath --show-trace

      - name: Evaluate junixbook
        run: nix eval .#nixosConfigurations.junixbook.config.system.build.toplevel.drvPath --show-trace
