name: "Nix Sync Update"

on:
  push:
    branches: [main]

jobs:
  sync:
    name: Sync other flake inputs
    if: github.actor == 'renovate[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.WALLPAPER_DEPLOY_KEY }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16

      - name: Update all flake inputs
        run: nix flake update

      - name: Evaluate junixos
        run: nix eval .#nixosConfigurations.junixos.config.system.build.toplevel.drvPath

      - name: Evaluate junixbook
        run: nix eval .#nixosConfigurations.junixbook.config.system.build.toplevel.drvPath

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(flake): update inputs"
          file_pattern: "flake.lock"
